package com.example.rds.type;

public enum GenreType {
	ARCHITECTURE,
	ART,
	BIOGRAPHY_AUTOBIOGRAPHY,
	BODY_MIND_SPIRIT,
	BUSINESS_ECONOMICS,
	COMICS_GRAPHIC_NOVELS,
	CHILDRENS_STORIES,
	COMPUTERS,
	COOKING,
	CRAFTS_HOBBIES,
	DESIGN,
	DRAMA,
	EDUCATION,
	FAMILY_RELATIONSHIPS,
	FICTION,
	FOREIGN_LANGUAGE_STUDY,
	HEALTH_FITNESS,
	HISTORY,
	HOUSE_HOME,
	HUMOR,
	JUVENILE_FICTION,
	JUVENILE_NONFICTION,
	LANGUAGE_ARTS_DISCIPLINES,
	LAW,
	LITERARY_COLLECTIONS,
	LITERARY_CRITICISM,
	MATHEMATICS,
	MEDICAL,
	MUSIC,
	NATURE,
	PERFORMING_ARTS,
	PETS,
	PHILOSOPHY,
	PHOTOGRAPHY,
	POETRY,
	POLITICAL_SCIENCE,
	PSYCHOLOGY,
	REFERENCE,
	RELIGION,
	SCIENCE,
	SELF_HELP,
	SOCIAL_SCIENCE,
	SPORTS_RECREATION,
	STUDY_AIDS,
	TECHNOLOGY_ENGINEERING,
	TRANSPORTATION,
	TRAVEL,
	TRUE_CRIME,
	OTHER;
	
	public static LargeGenreType classify(GenreType genre) {
		switch(genre) {
		case FICTION,JUVENILE_FICTION,POETRY:
			return LargeGenreType.FICTION;
		case BIOGRAPHY_AUTOBIOGRAPHY,HISTORY,TRUE_CRIME,
		RELIGION,JUVENILE_NONFICTION:
			return LargeGenreType.NON_FICTION;
		case LAW,TECHNOLOGY_ENGINEERING,COMPUTERS,BUSINESS_ECONOMICS:
			return LargeGenreType.PROFESSIONAL_TECHNICAL;
		case SCIENCE,NATURE,PHILOSOPHY,MATHEMATICS,MEDICAL,POLITICAL_SCIENCE,LITERARY_CRITICISM,LITERARY_COLLECTIONS,SOCIAL_SCIENCE:
			return LargeGenreType.ACADEMICS_RESEARCH;
		case COOKING,CRAFTS_HOBBIES,HOUSE_HOME,PETS,SPORTS_RECREATION,TRAVEL,TRANSPORTATION,SELF_HELP,CHILDRENS_STORIES:
			return LargeGenreType.PRACTICAL_HOBBIES;
		case ART,ARCHITECTURE,DESIGN,PHOTOGRAPHY,MUSIC,PERFORMING_ARTS,DRAMA:
			return LargeGenreType.ARTS_CULTURE;
		case EDUCATION,FOREIGN_LANGUAGE_STUDY,LANGUAGE_ARTS_DISCIPLINES,REFERENCE,STUDY_AIDS:
			return LargeGenreType.EDUCATION_STUDYAIDS;
		case HUMOR,COMICS_GRAPHIC_NOVELS:
			return LargeGenreType.ENTERTAINMENT;
		default:
			return LargeGenreType.OTHER;
		}
	}
}
