package com.example.rds.type;

public enum LargeGenreType {
	 FICTION,
	 NON_FICTION,
	 PROFESSIONAL_TECHNICAL,
	 ARTS_CULTURE,
	 EDUCATION_STUDYAIDS,
	 ENTERTAINMENT,
	 ACADEMICS_RESEARCH,
	 PRACTICAL_HOBBIES,
	 OTHER,
	 UNKNOWN
}
